name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Display
          template: classic
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_followup: yes
          plugin_followup_sections: user
          
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 100     # Limit recently used stats to last week
          plugin_languages_details: bytes-size, percentage 
          
          plugin_introduction: yes
          
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
          
#           plugin_habits: yes
#           plugin_habits_from: 200       # Use 200 events to compute habits
#           plugin_habits_days: 600        # Keep only events from last 14 days
#           plugin_habits_charts: yes     # Display charts section
#           plugin_habits_trim: yes       # Trim unused hours on daily chart
#           config_timezone: Europe/Geneva 
        
